# Site settings
title: Tech Blog
email: contact@samarthsinha.me
description: > # this means to ignore newlines until "baseurl:"
  Technical blog which contains concepts of 
  web development, architecture and many more from Java stack.
baseurl: "" # the subpath of your site, e.g. /blog/
keywords: "java, J2EE, spring mvc, spring framework, tomcat, mongodb, solr, redis, openshift,android,c"
url: "http://blog.samarthsinha.me" # the base hostname & protocol for your site
twitter_username: ankursamarth
github_username:  samarthsinha
linkedin_username: sinha-samarth

highlighter: pygments
current_profile: Senior Software Engineer
current_employer: Bharti Airtel Limited

# Build settings
markdown: kramdown

#analytics settings
analytics :
  provider : google 
  google : 
      tracking_id : 'UA-66360893-1'
exclude: ['CNAME','.idea/workspace.xml']
timezone: Asia/Calcutta
plugins:
  - jekyll-sitemap