# Site settings
title: Tech Blog
email: samarthsinha93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Technical blog which contains concepts of 
  web development, architecture and many more from Java stack.
baseurl: "" # the subpath of your site, e.g. /blog/
keywords: "java, J2EE, spring mvc, spring framework, tomcat, mongodb, solr, redis, openshift,android"
url: "http://samarthsinha.me" # the base hostname & protocol for your site
twitter_username: ankursamarth
github_username:  samarthsinha

# Build settings
markdown: kramdown

#analytics settings
analytics :
  provider : google 
  google : 
      tracking_id : 'UA-66360893-1'
